version: '3.3'
services:
  db:
    container_name: mariadb
    image: mariadb:10.6.16
    volumes:
      - /opt/test:/var/lib/mariadb
      - ./struct+data.sql:/docker-entrypoint-initdb.d/install.sql 
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: daw


  web:
    build: ./servlets
    depends_on:
      - db
    container_name: tomcat
    environment:
      - DB_HOST=db
    ports:
      - 8081:8080
    

  php:
    container_name: php
    build: ./php
    depends_on:
      - db
    environment:
      - DB_HOST=db
    ports:
      - 3001:80