FROM maven:3-jdk-11 as builder
RUN mkdir -p /build
COPY . /build
WORKDIR /build
RUN mvn clean compile package

FROM tomcat:7.0
COPY --from=builder /build/target /tom/target
WORKDIR /tom/target
RUN cp api.war /usr/local/tomcat/webapps/
EXPOSE 8080
CMD ["catalina.sh", "run"]
